name: olist_cdc
version: '1.0.0'
config-version: 2
profile: olist_cdc
model-paths: [models]
test-paths: [tests]
macro-paths: [macros]
on-run-start:
  - "{{ cdc_initialize_ledger() }}"
models:
  olist_cdc:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: incremental
      +incremental_strategy: delete+insert
      +on_schema_change: fail

